# Generated by Django 3.2.2 on 2021-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('url', models.URLField(blank=True, max_length=250)),
                ('image', models.ImageField(upload_to='portfo/images/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
